<?php
include 'header.php';

$buffer = '';


$result_data = <<<EOT
<?php
/**
Generated by flint-object-tool
at {date}
*/
\$result_{table_name} = null;

\$copy = array();
if (!isset(\$_SESSION['{table_name}_filters']))
{
    \$_SESSION['{table_name}_filters'] = array();
}
\$filters = &\$_SESSION['{table_name}_filters'];

if (count(\$_GET) > 1)
{
    foreach (\$_GET as \$k => \$v)
    {
        if (\$k == 'path') continue;
        if (\$v == 'ClearFilter')
        {
            if (isset(\$filters[\$k]))
            {
                unset(\$filters[\$k]);
            }
        }
        else
        {
            \$filters[\$k] = \$v;
        }
    }
    headloc('/' . \$_GET['path']);
}

if (count(\$action) > 0)
{
    if (\$action[0] == 'add')
    {
        if (count(\$_POST) > 0)
        {
            if (isset(\$_POST['add{table_name}']))
            {
{filter_input}

{query_insert}

{shmt_insert}
            }
            headloc('/{table_name}');
        }
        else
        {
            // TODO: add foreign data
            \$template = '{table_name}_add';
        }
    }
    else if (\$action[0] == 'edit')
    {
        if (count(\$_POST) > 0)
        {
            if (isset(\$_POST['edit{table_name}']) && isset(\$_POST['ID']))
            {
{filter_input}

{query_update}

{shmt_update}
            }
            headloc('/{table_name}');
        }
        if (count(\$action) == 2) {
            \$copy_id = intval(\$action[1]);
            \$q = sprintf('SELECT * FROM `{table_name}` WHERE `ID`=%d', \$copy_id);
            if (\$result = \$_mysqli->query(\$q)) {
                \$copy = \$result->fetch_assoc();
            }
            // TODO: add foreign data
            \$template = '{table_name}_edit';
        }
    }
    else if (\$action[0] == 'copy')
    {
        if (count(\$action) == 2) {
            \$copy_id = intval(\$action[1]);
            \$q = sprintf('SELECT * FROM `{table_name}` WHERE `ID`=%d', \$copy_id);
            if (\$result = \$_mysqli->query(\$q)) {
                \$copy = \$result->fetch_assoc();
            }
            // TODO: add foreign data
            \$template = '{table_name}_add';
        }
    }
    else if (\$action[0] == 'remove')
    {
        if (count(\$action) > 1)
        {
            \$id = intval(\$action[1]);
            \$q = 'DELETE FROM `{table_name}` WHERE `ID`=?';
            if (\$shmt = \$_mysqli->prepare(\$q))
            {
                \$shmt->bind_param('i', \$id);
                \$shmt->execute();
            }
        }
        headloc('/{table_name}');
    }
}
else
{
    \$where = 'WHERE ';
    foreach (\$filters as \$k => \$v)
    {
        if (strlen(\$where) > 0 && \$where != 'WHERE ')
        {
            \$where .= 'AND ';
        }
        if (is_numeric(\$v))
        {
            \$where .= "`{table_name}`.`{\$k}`=\$v ";
        }
        else
        {
            \$where .= "`{table_name}`.`{\$k}`='\$v' ";
        }
    }
    \$q = 'SELECT * FROM `{table_name}` '.(\$where == 'WHERE ' ? '' : \$where).' ORDER BY `Title`';
    \$result_{table_name} = \$_mysqli->query(\$q);
    \$template = '{table_name}';
}

EOT;

$Table = filter_input(INPUT_POST, 'Table', FILTER_SANITIZE_STRING);

$q = sprintf('SHOW FULL COLUMNS FROM `%s`', $Table);
$query_insert = sprintf("\t\t".'$q = \'INSERT INTO `%s`({FIELDS}) VALUES({VALUES})\';', $Table);
$query_update = sprintf("\t\t".'$q = \'UPDATE `%s` SET ', $Table);

$shmt = "\t\t".'if ($shmt = $_mysqli->prepare($q)){
            $shmt->bind_param(\'{SHMT_ISD}\', {SHMT_VARS});
            if(!$shmt->execute())
            {
                vd($shmt->error);
            }
        }';

if ($result_columns = $_mysqli->query($q))
{
    $query_insert_tmp_fields = '';
    $query_insert_tmp_values = '';

    $query_update_tmp = '';

    $shmt_tmp_isd = '';
    $shmt_tmp_vars = '';
    $filter_input = '';

    while ($row = $result_columns->fetch_row())
    {
        $name = $row[0];
        $type = $row[1];
        $shmt_type = '';
        if(strpos($type, 'float') !== false)
        {
            $type = 'FILTER_SANITIZE_NUMBER_FLOAT, FILTER_FLAG_ALLOW_FRACTION';
            $shmt_type = 'd';
        }
        else if (strpos($type, 'int') !== false)
        {
            $type = 'FILTER_SANITIZE_NUMBER_INT';
            $shmt_type = 'i';
        }
        else if (strpos($type, 'enum') !== false)
        {
            $type = 'FILTER_SANITIZE_STRING';
            $shmt_type = 's';
        }
        else if (strpos($type, 'varchar') !== false)
        {
            $type = 'FILTER_SANITIZE_STRING';
            $shmt_type = 's';
        }
        else
        {
            $type = 'FILTER_SANITIZE_STRING';
            $shmt_type = 's';
        }
        $filter_input .= "\t\t\${$name} = filter_input(INPUT_POST, '{$name}', {$type});\r\n";
        if ($name != 'ID')
        {
            $query_insert_tmp_fields .= "`{$name}`,";
            $query_insert_tmp_values .= '?,';
            $query_update_tmp .= "`{$name}`=?, ";

            $shmt_tmp_isd .= $shmt_type;
            $shmt_tmp_vars .= "\${$name}, ";
        }
    }

    $query_insert_tmp_fields = substr($query_insert_tmp_fields, 0, -1);
    $query_insert_tmp_values = substr($query_insert_tmp_values, 0, -1);
    $query_update_tmp = substr($query_update_tmp, 0, -2);
    $shmt_tmp_vars = substr($shmt_tmp_vars, 0, -2);

    $query_insert = str_replace('{FIELDS}', $query_insert_tmp_fields, $query_insert);
    $query_insert = str_replace('{VALUES}', $query_insert_tmp_values, $query_insert);
    $query_update = $query_update . $query_update_tmp . ' WHERE `ID`=?\';';

    $shmt_insert = str_replace('{SHMT_ISD}', $shmt_tmp_isd, $shmt);
    $shmt_insert = str_replace('{SHMT_VARS}', $shmt_tmp_vars, $shmt_insert);

    $shmt_tmp_isd .= 'i';
    $shmt_tmp_vars .= ', $ID';
    $shmt_update = str_replace('{SHMT_ISD}', $shmt_tmp_isd, $shmt);
    $shmt_update = str_replace('{SHMT_VARS}', $shmt_tmp_vars, $shmt_update);

    $result_data = str_replace('{filter_input}', $filter_input, $result_data);
    $result_data = str_replace('{query_insert}', $query_insert, $result_data);
    $result_data = str_replace('{shmt_insert}', $shmt_insert, $result_data);

    $result_data = str_replace('{query_update}', $query_update, $result_data);
    $result_data = str_replace('{shmt_update}', $shmt_update, $result_data);

    $result_data = str_replace('{table_name}', $Table, $result_data);
    $result_data = str_replace('{date}', date('r'), $result_data);

    $buffer = $result_data;
}
?>
<textarea rows="44" cols="250"><?=$buffer?></textarea>
<?php
include 'footer.php';
?>
